# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - vladzaharia
    commit-message:
      prefix: "[npm] "
    labels:
      - "dependencies/npm"
      - "dependencies"
    open-pull-requests-limit: 5
    groups:
      nx:
        patterns:
          - "*nx*"
      typescript:
        patterns:
          - "tslib"
          - "typescript"
          - "ts-node"
      vitejs:
        patterns:
          - "vite*"
          - "*vitest*"
          - "vitejs*"
      react:
        patterns:
          - "*react*"
          - "use-*"
      mui:
        patterns:
          - "@mui*"
          - "@emotion*"
      mapbox:
        patterns:
          - "*mapbox*"
          - "*react-map-gl*"
      kysely:
        patterns:
          - "kysely*"
      eslint:
        patterns:
          - "*eslint*"
      fontawesome:
        patterns:
          - "@fortawesome*"
      moment:
        patterns:
          - "moment*"
      cloudflare:
        patterns:
          - "*cloudflare*"
          - "wrangler"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - vladzaharia
    commit-message:
      prefix: "[Github Actions] "
    labels:
      - "dependencies/gha"
      - "dependencies"
    open-pull-requests-limit: 0
