name = "scuba"
main = "src/index.ts"
compatibility_date = "2023-07-05"
usage_model = "bundled"
site = { bucket = "./dist" }
triggers = { crons = [] }

[env.dev]
route = { pattern = "dev.scuba.vlad.gg", custom_domain = true }
vars = { ENVIRONMENT = "dev", BASE_URL="https://dev.scuba.vlad.gg" }

[env.staging]
route = { pattern = "staging.scuba.vlad.gg", custom_domain = true }
vars = { ENVIRONMENT = "staging", BASE_URL="https://staging.scuba.vlad.gg" }

[env.live]
route = { pattern = "scuba.vlad.gg", custom_domain = true }
vars = { ENVIRONMENT = "live", BASE_URL="https://scuba.vlad.gg" }
