name: PR Build and Deploy

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    uses: ./.github/workflows/shared-build.yml
    secrets: inherit

  test:
    needs: ['build']
    uses: ./.github/workflows/shared-test.yml
    secrets: inherit
    permissions: write-all

  lint:
    needs: ['build']
    uses: ./.github/workflows/shared-lint.yml
    secrets: inherit
    permissions:
      security-events: write

  format:
    needs: ['build']
    uses: ./.github/workflows/shared-format.yml
    secrets: inherit
    permissions:
      security-events: write

  deploy:
    needs: ['build', 'test']
    uses: ./.github/workflows/shared-deploy.yml
    with:
      environment: staging
      baseUrl: https://staging.track.vlad.gg
    secrets: inherit

  e2e:
    needs: ['deploy']
    uses: ./.github/workflows/shared-e2e.yml
    with:
      environment: staging
    secrets: inherit
    permissions: write-all

  merge-debug:
    name: Debug auto-merger
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.actor }}
      - run: echo ${{ github.triggering_actor }}
      - run: echo ${{ github.event.pull_request.labels.*.name }}

  merge:
    name: Auto-merge PR
    needs: ['e2e']
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' || (github.triggering_actor == 'vladzaharia' && contains(github.event.pull_request.labels.*.name, 'auto-merge')) }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Merge PR
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
