name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      baseUrl:
        required: true
        type: string
    secrets:
      CLOUDFLARE_API_TOKEN:
        required: true
      CLOUDFLARE_ACCOUNT_ID:
        required: true
      FONTAWESOME_API_TOKEN:
        required: true

jobs:
  deploy:
    name: Deploy to ${{ inputs.environment }} with Wrangler
    runs-on: ubuntu-latest
    concurrency: ${{ inputs.environment }}
    environment:
      name: ${{ inputs.environment }}
      url: ${{ inputs.baseUrl }}

    steps:
    - name: Checkout files
      uses: actions/checkout@v3
    - name: Use Node.js v20.x
      uses: actions/setup-node@v3
      with:
        node-version: v20.x
        cache: 'npm'
    - name: Install NPM packages
      run: npm ci --ignore-scripts
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: dist
        path: tracker-server/dist
    - name: Deploy to Cloudflare Workers (${{ inputs.environment }})
      uses: cloudflare/wrangler-action@2.0.0
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        workingDirectory: tracker-server
        command: deploy --env ${{ inputs.environment }}
