name: Build

on:
  workflow_call:
    secrets:
      FONTAWESOME_API_TOKEN:
        required: true

jobs:
  format:
    name: Format with Prettier
    runs-on: ubuntu-latest
    permissions:
      security-events: write

    steps:
    - name: Checkout files
      uses: actions/checkout@v3
    - name: Use Node.js v20.x
      uses: actions/setup-node@v3
      with:
        node-version: v20.x
        cache: 'npm'
    - name: Install NPM packages
      run: npm ci --ignore-scripts
      env:
        FONTAWESOME_API_TOKEN: ${{ secrets.FONTAWESOME_API_TOKEN }}
    - name: 'Format with Prettier'
      run: npx nx run-many -t format --configuration ci
      env:
        NX_BRANCH: "${{ github.ref_name }}"
