name: Test

on:
  workflow_call:
    secrets:
      FONTAWESOME_API_TOKEN:
        required: true

jobs:
  test:
    name: Test with Vitest
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - name: Checkout files
      uses: actions/checkout@v3
    - name: Use Node.js v20.x
      uses: actions/setup-node@v3
      with:
        node-version: v20.x
        cache: 'npm'
    - name: Install NPM packages
      run: npm ci --ignore-scripts
      env:
        FONTAWESOME_API_TOKEN: ${{ secrets.FONTAWESOME_API_TOKEN }}
    - name: Run Vitest tests
      run: npx nx run-many -t test --configuration ci --skip-nx-cache
      env:
        NX_BRANCH: "${{ github.ref_name }}"
    - name: Upload test artifacts
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test
        path: coverage/
        retention-days: 7
    - name: Report test results
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Unit test results
        path: "coverage/tracker-app/junit.xml,coverage/tracker-server/junit.xml"
        reporter: jest-junit
