name: Build

on:
  workflow_call:
    secrets:
      FONTAWESOME_API_TOKEN:
        required: true

jobs:
  build:
    name: Build with TSC/Vite
    runs-on: ubuntu-latest

    steps:
    - name: Checkout files
      uses: actions/checkout@v3
    - name: Use Node.js v18.x
      uses: actions/setup-node@v3
      with:
        node-version: v18.x
        cache: 'npm'
    - name: Set FontAwesome CI token
      run: |
        npm config set '@fortawesome:registry' https://npm.fontawesome.com/
        npm config set '//npm.fontawesome.com/:_authToken' "${{ secrets.FONTAWESOME_API_TOKEN }}"
    - name: Install NPM packages
      run: npm ci --ignore-scripts
      env:
        FONTAWESOME_API_TOKEN: ${{ secrets.FONTAWESOME_API_TOKEN }}
    - name: 'Build and prepare artifacts'
      run: npx nx run tracker-server:build-ci
      env:
        NX_BRANCH: "${{ github.ref_name }}"
    - name: 'Upload server dist artifacts'
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: tracker-server/dist/
        retention-days: 7
